<!DOCTYPE html>
<html lang="zh-CN">
    <head>
  <!-- 元数据 -->
  <meta charset="utf-8">
  
  
  <title>异常 | simon·yian&#39;Blog</title>
  <meta name="author" content="simon·yi an" />
  <meta http-equiv="Cache-Control" content="no-transform" />
  <meta http-equiv="Cache-Control" content="no-siteapp" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="robots" content="index,follow" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <meta name="format-detection" content="telphone=no, email=no" />
  
    <meta name="keywords" content="" />
  
  <meta name="description" content="***&amp;emsp;&amp;emsp;&amp;emsp;&amp;emsp;&amp;emsp;&amp;emsp;&amp;emsp;Java基础学习打卡第2天">
<meta property="og:type" content="article">
<meta property="og:title" content="异常">
<meta property="og:url" content="https://simon-yian.github.io/2022/08/10/xianTrain20-Exception/index.html">
<meta property="og:site_name" content="simon·yian&#39;Blog">
<meta property="og:description" content="***&amp;emsp;&amp;emsp;&amp;emsp;&amp;emsp;&amp;emsp;&amp;emsp;&amp;emsp;Java基础学习打卡第2天">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://s1.ax1x.com/2022/08/10/v3vx4e.jpg">
<meta property="article:published_time" content="2022-08-10T12:00:10.000Z">
<meta property="article:modified_time" content="2022-08-10T12:23:08.000Z">
<meta property="article:author" content="simon·yi an">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://s1.ax1x.com/2022/08/10/v3vx4e.jpg">
  
  <!-- 站点验证相关 -->
  
    
    
    
  
  <!-- 样式表文件 -->
  <link rel="stylesheet" id="kratos-css" href="/css/kratosr.min.css" media="all"></script>
  
    <link rel="stylesheet" id="darkmode-css" href="/css/kr-color-dark.min.css" media="(prefers-color-scheme: dark)"></script>
    <script src="/js/kr-dark.min.js"></script>
  
  
    <link rel="stylesheet" id="highlight-css" href="/css/highlight/night-eighties.min.css" media="all"></script>
  
  
  <link rel="stylesheet" id="fontawe-css" href="/vendors/font-awesome@4.7.0/css/font-awesome.min.css" media="all"></script>
  <link rel="stylesheet" id="nprogress-css" href="/vendors/nprogress@0.2.0/nprogress.css" media="all"></script>
  
  
    <link rel="stylesheet" href="/vendors/aplayer@1.10.1/dist/APlayer.min.css"></script>
  
  
    <link rel="stylesheet" href="/vendors/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css"></script>
  
  <!-- 不得不预先加载的一些JS文件 -->
  <script src="/vendors/jquery@3.6.0/dist/jquery.min.js"></script>
  
    <script src="/vendors/qrcode_js@1.0.0/qrcode.min.js"></script>
  
  
  <style>
    
      .kratos-cover.kratos-cover-2 {
        background-image: url('/images/banner.webp');
      }
    
    
      @media(min-width:768px) {
        body.custom-background {
          background-image: url('/images/bg.webp');
        }
      }
    
  </style>
  
<meta name="generator" content="Hexo 5.4.0"></head>


    <body class="custom-background">
        <div id="kratos-wrapper">
    <div id="kratos-page">
        <div id="kratos-header">
            <header id="kratos-desktop-topnav" class="kratos-topnav">
                <div class="container">
                    <div class="nav-header">
                        <nav id="kratos-menu-wrap">
                            <ul id="kratos-primary-menu" class="sf-menu">
                                
                                    
                                    
                                
                            </ul>
                        </nav>
                    </div>
                </div>
            </header>
            <header id="kratos-mobile-topnav" class="kratos-topnav">
                <div class="container">
                    <div class="color-logo"><a href="/">simon·yian&#39;Blog</a></div>
                    <div class="nav-toggle">
                        <a class="kratos-nav-toggle js-kratos-nav-toggle">
                            <i></i>
                        </a>
                    </div>
                </div>
            </header>
        </div>
        <div class="kratos-start kratos-hero-2">
            <!-- <div class="kratos-overlay"></div> -->
            <div class="kratos-cover kratos-cover-2 text-center">
                <div class="desc desc2 animate-box">
                    <a href="/">
                        <h2>simon·yian&#39;Blog</h2> <br />
                        <span></span>
                    </a>
                </div>
            </div>
        </div>

        <div id="kratos-blog-post">
            <div class="container">
                <div id="main" class="row">
                    

        

            <section class="col-md-8">

        

            <article itemscope itemtype="https://schema.org/Article">
    
    <link itemprop="mainEntityOfPage" href="https://simon-yian.github.io/2022/08/10/xianTrain20-Exception/">
    <div class="kratos-hentry kratos-post-inner clearfix">
        <header class="kratos-entry-header">
            
                <h1 class="kratos-entry-title text-center" itemprop="name headline">异常</h1>
            
            
            <ul class="kratos-post-meta text-center">
                <li><time datetime="2022-08-10T12:00:10.000Z" itemprop="datePublished"><i class="fa fa-calendar"></i> 2022-08-10</time></li>
                <li itemprop="author" itemscope itemtype="https://schema.org/Person">
                    <i class="fa fa-user"></i> 作者 <span itemprop="name">simon·yi an</span>
                </li>
                <li>
                    <i class="fa fa-edit"></i> 
                    
                    
                        ~14.44K
                    
                    字
                </li>
                
            </ul>
        </header>
        <div class="kratos-post-content">
            
            <div id="expire-alert" class="alert alert-warning hidden" role="alert">
                <div class="icon"><i class="fa fa-warning"></i></div>
                <div class="text"><p>本文最后编辑于 <time datetime="1660134188000"></time> 前，其中的内容可能需要更新。</p></div>
            </div>
            
            
            
            <hr />
            <div itemprop="articleBody"><p>***&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Java基础学习打卡第2天</p>
<span id="more"></span>
<p>如果看一门编程语言是否健壮，那么是否提供异常处理机制就是很重要的判断标准之一，除了传统的C语言以外，目前主流的编程语言都提供了成熟的异常机制，例如C#，Python等。异常机制可以使程序中的异常处理代码和业务代码分离，保证程序更加的优雅，提高程序的健壮性。<br>Java 的异常机制主要依赖干 try、catch、finally、throw 和 throws 五个关键字，其中 try 关键字后紧跟一个花括号扩起来的代码块（花括号不可省略），简称 try 块，它里面放置可能引发异常的代码。catch后对应异常类型和一个代码块，用于表明该 catch 块用于处理这种类型的代码块。多个 catch 块后还可以跟一个 finally 块，finally 块用于回收在 try 块里打开的物理资源，异常机制会保证 finally 块总被执行。 throws 关键字主要在方法签名中使用，用于声明该方法可能抛出的异常；而 throw 用于抛出—个实际的异常，throw 可以单独作为语句使用，抛出一个具体的异常对象 。<br>Java 7 进一步增强了异常处理机制的功能，包括带资源的 try 语句、捕获多异常的 catch 两个新功能，这两个功能可以极好地简化异常处理。 开发者希望所有的错误都能在编译阶段被发现，就是在试图运行程序之前排除所有错误，但这是不现实的，余下的问题必须在运行期间得到解决。Java将异常分为两种，Checked 异常和 Runtime 异常， Java 认为 Checked 异常都是可以在编译阶段被处理的异常，所以它强制程序运行前处理所有的 Checked 异常；而 Runtime 异常则无须处理。</p>
<p>13.1 异常类的继承体系<br>Java提供了丰富的异常类，这些类有着严格的继承关系，如下图：<br><a target="_blank" rel="noopener" href="https://imgtu.com/i/v3vx4e"><img src="https://s1.ax1x.com/2022/08/10/v3vx4e.jpg" alt="v3vx4e.jpg"></a><br>从图示中可以看出，Java把所有的非正常情况分为两大类：异常（Exception）和错误（Error），他们都是Throwable的子类。</p>
<p>Error：和虚拟机有关的问题，如系统崩溃、虚拟机错误等，这些错误无法恢复或者不可能被抓取，将导致应用程序中断，应用程序通常无法处理这些错误，因此不应该用异常处理方法来处理Error。同样，也不能在throws字句中声明该方法可能抛出Error。<br>Exception：程序中出现的非正常情况，其中异常又分为两类，RuntimeException（运行时异常）和CheckedException（检查时异常），这两类异常都是Exception的子类，其中RuntimeException及其子类不需要开发者显示处理。如果一个Exception没有继承RuntimeException类，则属于CheckedException，这类异常通常需要开发者显示处理。否则会出现编译错误。<br>下面，先通过示例来演示运行时异常和检查时异常的区别</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br></pre></td><td class="code"><pre><span class="line"></span><br><span class="line"></span><br><span class="line">package cn.bytecollege;</span><br><span class="line"></span><br><span class="line">public class Student &#123;</span><br><span class="line">	/**</span><br><span class="line">	 * 定义方法，该方法抛出算术异常</span><br><span class="line">	 * 算术异常是运行时异常</span><br><span class="line">	 * @throws ArithmeticException</span><br><span class="line">	 */</span><br><span class="line">	public void say() throws ArithmeticException&#123;</span><br><span class="line">		</span><br><span class="line">	&#125;</span><br><span class="line">	/**</span><br><span class="line">	 * 定义方法，该方法抛出检查时异常</span><br><span class="line">	 * 检查时异常要求开发者必须显示处理</span><br><span class="line">	 * @throws ClassNotFoundException</span><br><span class="line">	 */</span><br><span class="line">	public void hello() throws ClassNotFoundException&#123;</span><br><span class="line">		</span><br><span class="line">	&#125;</span><br><span class="line">	</span><br><span class="line">	public static void main(String[] args) &#123;</span><br><span class="line">		</span><br><span class="line">		Student s = new Student();</span><br><span class="line">		//因为该方法抛出的是运行时异常，即使不处理也不会发生编译错误</span><br><span class="line">		s.say();</span><br><span class="line">		//该方法抛出的是检查时异常，要求开发者显示处理</span><br><span class="line">		//如果不处理则编译错误</span><br><span class="line">		s.hello();</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>在上面的示例中，定义了Student类以及两个实例方法：<br>其中say()方法抛出了一个ArithmeticException，因为ArithmeticException继承了RuntimeException，所以它是一个运行时异常，因此，在上述代码第25行调用该方法时，即使没有显式的处理该异常，程序也不会出现编译错误。<br>hello()方法抛出了ClassNotFoundException，ClassNotFoundException没有继承RuntimeException，因此是一个检查时异常，而检查时异常需要开发者显式处理，如果不处理，则会出现编译错误。</p>
<p>13.2 异常处理机制<br>对于计算机程序而言，没有人能保证自己写的程序永远不会出错！就算程序没有错误，你能保证用户总是按你的意愿来输入? 就算用户都是非常”聪明而且配合”的，你能保证运行该程序的操作系统永远稳定？你能保证运行该程序的硬件不会突然坏掉？你能保证网络永远通畅？<br>对于一个程序设计人员，需要尽可能地预知所有可能发生的情况，尽可能地保证程序在所有糟糕的情形下都可以运行。也就是说要时时刻刻考虑程序的健壮性。<br>Java 的异常处理机制可以让程序具有极好的容错性，让程序更加健壮。当程序运行出现意外情形时，系统会自动生成一个 Exception 对象来通知程序，从而实现将”业务功能实现代码”和”错误处理代码”分离，提供更好的可读性。 </p>
<p>13.2.1 try…catch捕获异常<br>正如前面示例中编写的代码，在代码28行如果不做任何处理，将会出现编译错误，代码也就无法执行。为了解决这个问题，可以使用try…catch捕获异常，并对异常进行处理，如果执行try语句块中的代码出现异常，系统会自动生成一个异常对象，该对象被提交给Java运行时环境，这个过程被称为throw（抛出）异常。<br>当Java运行时环境受到异常对象时，会寻找对应处理该异常对象的catch块，如果找到合适的catch块，则把该异常对象交给catch块处理，这个过程叫做catch（捕获）异常；如果Java运行时环境找不到捕获异常的catch块，则运行时环境终止，Java程序也将退出。<br>下面将演示上例中代码中异常的处理方式：</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line"></span><br><span class="line">public static void main(String[] args) &#123;</span><br><span class="line">		</span><br><span class="line">		Student s = new Student();</span><br><span class="line">		//因为该方法抛出的是运行时异常，即使不处理也不会发生编译错误</span><br><span class="line">		s.say();</span><br><span class="line">		//该方法抛出的是检查时异常，要求开发者显示处理</span><br><span class="line">		//如果不处理则编译错误</span><br><span class="line">		try &#123;</span><br><span class="line">			s.hello();</span><br><span class="line">		&#125; catch (ClassNotFoundException e) &#123;</span><br><span class="line">			e.printStackTrace();</span><br><span class="line">		&#125;</span><br><span class="line">	&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p>从上面的程序可以看出，将第9行可能抛出异常的代码放入了try语句块中，当这一行代码发生异常时，就会到后续的catch语句块中寻找与之对应的异常，如果找到则进入catch语句块中继续执行。避免了程序的中断。<br>接下来，通过示例来学习当代码发生异常时如果catch中有对应的异常和没有对应的异常时发生的情况。</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line">package cn.bytecollege;</span><br><span class="line">import java.lang.reflect.Field;</span><br><span class="line">public class ReflectDemo &#123;</span><br><span class="line">	public static void main(String[] args) &#123;</span><br><span class="line">		//创建Student对象</span><br><span class="line">		Student s = new Student();</span><br><span class="line">		Class clazz = s.getClass();</span><br><span class="line">		try &#123;</span><br><span class="line">			Field field = clazz.getDeclaredField(&quot;name&quot;);</span><br><span class="line">		&#125; catch (NoSuchFieldException e) &#123;</span><br><span class="line">			e.printStackTrace();</span><br><span class="line">			System.out.println(&quot;未找到该属性&quot;);</span><br><span class="line">		&#125; </span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p>在上面的程序中，使用了反射获取Student中的name变量，因为在Student中并没有定义name变量，所有当代码运行至第9行时，一定会发生NoSuchFieldException，并且在try后的catch中就存在与之对应的异常处理语句。程序将进入对应的catch语句块中，并向下执行。运行结果如下图所示：<br>image.png<br>如果程序发生异常时在catch语句中没有找到对应的异常，那么程序将终止运行，通过下面的示例来演示这种情况。</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line">package cn.bytecollege.ExceptionDemo;</span><br><span class="line"></span><br><span class="line">import java.lang.reflect.Field;</span><br><span class="line"></span><br><span class="line">public class ReflectDemo &#123;</span><br><span class="line">        public static void main(String[] args) &#123;</span><br><span class="line">            //创建Student对象</span><br><span class="line">            Student s = new Student();</span><br><span class="line">            Class clazz = s.getClass();</span><br><span class="line">            try &#123;</span><br><span class="line">                //此时会出现编译错误，提示必须对NoSuchFieldException进行捕获或者生命以便抛出</span><br><span class="line">                Field field = clazz.getDeclaredField(&quot;name&quot;);</span><br><span class="line">            &#125; catch (NullPointerException e) &#123;</span><br><span class="line">                e.printStackTrace();</span><br><span class="line">                System.out.println(&quot;未找到该属性&quot;);</span><br><span class="line">            &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p>image.png</p>
<p>13.2.2 Java 7提供的多异常捕获<br>在Java 7以前，每个catch块只能捕获一种类型的异常；但是从Java 7开始，一个catch块可以捕获多种类型的异常。<br>使用catch块捕获多种类型异常时需要注意以下两点：</p>
<p>捕获多种类型异常时，多种异常类型之间使用 | 隔开<br>捕获多种类型异常时，异常变量有隐式的final修饰，因此程序不能对异常变量重新赋值<br>我们重构上一小节的程序：</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br></pre></td><td class="code"><pre><span class="line">package cn.bytecollege;</span><br><span class="line">import java.lang.reflect.Field;</span><br><span class="line">public class ReflectDemo &#123;</span><br><span class="line">	public static void main(String[] args) &#123;</span><br><span class="line">		//创建Student对象</span><br><span class="line">		Student s = new Student();</span><br><span class="line">		Class clazz = s.getClass();</span><br><span class="line">		try &#123;</span><br><span class="line">			Field field = clazz.getDeclaredField(&quot;name&quot;);</span><br><span class="line">		&#125; catch (NoSuchFieldException | SecurityException e) &#123;</span><br><span class="line">			//因为e是隐式final修饰的，所以不能重新赋值</span><br><span class="line">//			e = new ArithmeticException();</span><br><span class="line">			e.printStackTrace();</span><br><span class="line">		&#125;</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p>通过重构代码可以发现在一个catch中捕获了NoSuchFieldException和SecurityException两个异常，在代码12行重新对e赋值发现编译出错，这是因为变量e是使用隐式的final修饰的，final修饰的变量初始化后不能被重新赋值。所以会编译错误。</p>
<p>13.2.2 使用finally回收资源<br>在开发中经常会打开一些资源，例如数据库连接，网络连接和磁盘文件等，这些资源在打开后都必须要显式回收。并且这些资源必须要进行回收，否则会持续占用内存资源。而且不会释放。<br>为了保证资源一定能被回收，异常处理机制提供了finally块，不管try块中的代码是否出现异常，也不管哪个catch语句块被执行，甚至在try块或者catch块中执行了return语句，finally中的代码总会被执行。其语法结构如下：</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line">try&#123;</span><br><span class="line">    //代码</span><br><span class="line">&#125;catch(Exception e1)&#123;</span><br><span class="line"> 	//代码   </span><br><span class="line">&#125;catch(Exception e2)&#123;</span><br><span class="line"> 	//代码   </span><br><span class="line">&#125;finally&#123;</span><br><span class="line"> 	//资源回收   </span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p>异常处理语法结构中只有 try 块是必需的，也就是说，如果没有 try 块，则不能有后面的 catch 块和 finally 块；catch 块和 finally 块都是可选的，但 catch 块和 finally 块至少出现其中之一，也可以同时出现;可以有多个 catch 块，捕获父类异常的 catch 块必须位于捕获子类异常的后面；但不能只有 try 块，既没有 catch 块，也没有 finally 块；多个 catch 块必须位于 try 块之后，finally 块必须位于所有的 catch块之后。并且finally语句块不能单独出现，只能和try…catch搭配使用。<br>下面，通过示例来了解finally的作用：</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br></pre></td><td class="code"><pre><span class="line">package cn.bytecollege;</span><br><span class="line">/**</span><br><span class="line"> * 本例将演示finally语句块一定会执行</span><br><span class="line"> * @author MR.W</span><br><span class="line"> */</span><br><span class="line">public class FinallyDemo &#123;</span><br><span class="line">	public static void main(String[] args) &#123;</span><br><span class="line">		try &#123;</span><br><span class="line">			//此处会抛出ArithmeticException</span><br><span class="line">			System.out.println(&quot;try&quot;);</span><br><span class="line">			int i = 5/0;</span><br><span class="line">		&#125;catch (ArithmeticException e) &#123;</span><br><span class="line">			//catch语句块捕获了该异常</span><br><span class="line">			System.out.println(&quot;catch&quot;);</span><br><span class="line">			e.printStackTrace();</span><br><span class="line">		&#125;finally &#123;</span><br><span class="line">			//进入finally语句块</span><br><span class="line">			System.out.println(&quot;finally&quot;);</span><br><span class="line">		&#125;</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p>在上面的程序中第10行因为用整数除0，所以会抛出ArithmeticException，在try后的catch语句块中可以捕获该异常，并执行catch中的代码，catch后还有finally语句块，finally语句块的特点是不管是否会抛出异常，finally中的语句都会执行，所以程序结果运行如下图：<br>image.png<br>修改上例中的代码，即使try语句块中的代码不抛出异常，finally中的代码也会执行。</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br></pre></td><td class="code"><pre><span class="line">package cn.bytecollege;</span><br><span class="line">/**</span><br><span class="line"> * 本例将演示finally语句块一定会执行</span><br><span class="line"> * @author MR.W</span><br><span class="line"> */</span><br><span class="line">public class FinallyDemo &#123;</span><br><span class="line">	public static void main(String[] args) &#123;</span><br><span class="line">		try &#123;</span><br><span class="line">			System.out.println(&quot;try&quot;);</span><br><span class="line">			int i = 5/1;</span><br><span class="line">		&#125;catch (ArithmeticException e) &#123;</span><br><span class="line">			//catch语句块捕获了该异常</span><br><span class="line">			System.out.println(&quot;catch&quot;);</span><br><span class="line">			e.printStackTrace();</span><br><span class="line">		&#125;finally &#123;</span><br><span class="line">			//进入finally语句块</span><br><span class="line">			System.out.println(&quot;finally&quot;);</span><br><span class="line">		&#125;</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p>上面的代码中try语句块中被不会抛出异常，所以代码不会进入catch语句块中，但是仍然会进入finally语句块中并执行代码，结果如下图：<br>image.png<br>除此以外Java还提供了增强版的try-with-resource语法，这节内容将在下一章中详细讲解。</p>
<p>13.2 使用throws声明抛出异常<br>throws用于方法头中抛出异常，当定义一个方法并且该方法不知道如何处理这种类型的异常时，该异常交由调用者处理；如果main方法也不知道如何处理这种类型的异常，也可以使用throws声明抛出异常，该异常将交有JVM处理。JVM对异常的处理方法是，打印异常的跟踪栈信息，并终止程序的运行。<br>throws声明抛出异常只能在方法签名中使用，throws可以声明抛出一个异常类，多个异常类之间用逗号隔开。语法格式如下：</p>
<p>throws Exception1,Exception2…<br>如果某段代码中调用了一个带throws声明的方法，该方法抛出了Checked异常，则表明该方法要求调用者来处理该异常。也就是说方法的调用者要么在try语句块中显示捕获该异常，要么放在另一个带throws声明抛出的方法中。下面的示例将演示这种用法。</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br></pre></td><td class="code"><pre><span class="line">package cn.bytecollege;</span><br><span class="line"></span><br><span class="line">import java.sql.SQLException;</span><br><span class="line"></span><br><span class="line">public class Teacher &#123;</span><br><span class="line">	</span><br><span class="line">	public void say() throws ClassNotFoundException,SQLException&#123;</span><br><span class="line">		</span><br><span class="line">	&#125;</span><br><span class="line">	public static void main(String[] args) &#123;</span><br><span class="line">		Teacher t = new Teacher();</span><br><span class="line">		</span><br><span class="line">		try &#123;</span><br><span class="line">			t.say();</span><br><span class="line">		&#125; catch (ClassNotFoundException e) &#123;</span><br><span class="line">			e.printStackTrace();</span><br><span class="line">		&#125; catch (SQLException e) &#123;</span><br><span class="line">			e.printStackTrace();</span><br><span class="line">		&#125;</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p>上面的程序中定义了Teacher类，在Teacher中定义了say()方法，并且该方法在方法头中使用throws抛出了ClassCastException，SQLException，在main方法中创建了Teacher对象t，并调用了say方法，因为ClassNotFoundException，SQLException都是Checked异常，所以调用say方法时，必须显示的处理这两个异常，在上例中使用了try…catch对异常进行了处理。当然也可以在调用say方法代码所在的方法头继续使用throws抛出异常，但是由于say方法是在main方法中调用的，也就是说如果继续throws异常的话，会抛给虚拟机，但是并不建议将异常抛给虚拟机。下面的程序将演示这种情况</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line">package cn.bytecollege;</span><br><span class="line">import java.sql.SQLException;</span><br><span class="line">public class Teacher &#123;</span><br><span class="line">	public void say() throws ClassCastException,SQLException&#123;</span><br><span class="line">	&#125;</span><br><span class="line">	public static void main(String[] args) throws ClassCastException, SQLException &#123;</span><br><span class="line">		Teacher t = new Teacher();</span><br><span class="line">		t.say();</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p>上面的程序中第8行say方法抛出了异常，但是并没有处理，而是直接向上抛出，因为say方法是在main方法中调用的，如果继续抛出异常，main方法只能将异常抛给虚拟机。</p>
<p>13.3 使用throw抛出异常<br>当程序出现错误时，系统会自动抛出异常；除此之外，Java也允许程序自行抛出异常，自行抛出异常使用throw语句来完成（注意此处的throw没有后面的s，与前面声明抛出的throws是有区别的）。</p>
<p>13.3.1 抛出异常<br>很多时候，系统是否要抛出异常，可能需要根据应用的业务需求来决定，如果程序中的数据、执行与既定的业务需求不符，这就是一种异常。<br>由于与业务需求不符合产生的异常，必须由程序员来决定抛出，系统无法抛出这种异常。如果需要在程序中自行抛出异常，则应使用throw语句，throw语句可以单独使用，throw语句抛出的不是异常类，而是一个异常实例，而且每次只能抛出一个异常实例。throw语句的语法格式如下：</p>
<p>throw ExceptionInstance;<br>在开发中登录是常见的业务，当用户输入用户名和密码后，开发者需要对用户名进行校验其合法性，例如长度符合规定，如果不符合规定，就可以抛出一个异常。下面的程序将演示throw的用法：</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line">package cn.bytecollege;</span><br><span class="line"></span><br><span class="line">import java.util.Scanner;</span><br><span class="line"></span><br><span class="line">public class StringValid &#123;</span><br><span class="line">	public static void main(String[] args) &#123;</span><br><span class="line">		Scanner sc = new Scanner(System.in);</span><br><span class="line">		String username = sc.next();</span><br><span class="line">		valid(username);</span><br><span class="line">	&#125;</span><br><span class="line">	public static void valid(String username) &#123;</span><br><span class="line">		int length = username.length();</span><br><span class="line">		if(length&gt;12||length&lt;6) &#123;</span><br><span class="line">			throw new RuntimeException(&quot;用户名长度不合法&quot;);</span><br><span class="line">		&#125;</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p>上面的程序中，在valid方法中，如果用户输入的用户名长度小于6或者大于12就使用throw在方法内抛出异常，也就是说当用户名长度小于6或者大于12程序认定这是异常。当Java运行时接收到用户自行抛出的异常时，同样会中止当前的执行流，跳到该异常对应的catch块，由该catch块来处理该异常。也就是说，不管是系统自动抛出的异常，还是程序员手动抛出的异常，Java运行时环境对异常的处理没有任何差别。<br>如果throw语句抛出的异常是Checked异常，则该throw语句要么处于try块里，显式捕获该异常，要么放在一个带throws声明抛出的方法中，即把该异常交给该方法的调用者处理；如果throw语句抛出的异常是Runtime异常，则该语句无须放在try块里，也无须放在带throws声明抛出的方法中；程序既可以显式使用try…catch来捕获并处理该异常，也可以完全不理会该异常，把该异常交给该方法调用者处理。例如下面例子程序。</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br></pre></td><td class="code"><pre><span class="line">package cn.bytecollege;</span><br><span class="line"></span><br><span class="line">import java.util.Scanner;</span><br><span class="line"></span><br><span class="line">public class StringValid2 &#123;</span><br><span class="line">	public static void main(String[] args) &#123;</span><br><span class="line">		Scanner sc = new Scanner(System.in);</span><br><span class="line">		String username = sc.next();</span><br><span class="line">		try &#123;</span><br><span class="line">			valid(username);</span><br><span class="line">		&#125; catch (Exception e) &#123;</span><br><span class="line">			e.printStackTrace();</span><br><span class="line">		&#125;</span><br><span class="line">	&#125;</span><br><span class="line">	public static void valid(String username) throws Exception &#123;</span><br><span class="line">		int length = username.length();</span><br><span class="line">		if(length&gt;12||length&lt;6) &#123;</span><br><span class="line">			throw new Exception(&quot;用户名长度不合法&quot;);</span><br><span class="line">		&#125;</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p>在上面的程序中修改了valid方法，当用户输入的用户名长度不合法时，使用throw抛出了一个Checked异常，因此在方法头上需要使用throws声明抛出异常（当然，也可以在valid方法中使用try…catch处理，但是这么做没有意义，相当于自己的异常自己处理了，那么调用者也不清楚输入的数据是否合法）。当该方法抛出Checked异常后，也要求方法的调用者显示的处理，所以在main方法中显示了处理了异常。</p>
<p>13.4 自定义异常类<br>在上一小节学习了如何使用throw在方法内抛出异常，但是在程序开发选择抛出异常时，应该选择合适的异常类，从而可以明确地描述该异常情况。在这种情形下，应用程序常常需要抛出自定义异常。用户自定义异常都应该继承Exception基类，如果希望自定义Runtime异常，则应该继承RuntimeException基类。定义异常类时通常需要提供两个构造器：一个是无参数的构造器；另一个是带一个字符串参数的构造器，这个字符串将作为该异常对象的描述信息（也就是异常对象的getMessage()方法的返回值）。例如上一小节的示例，直接使用了RuntimeException或者Exception，这样并不能很清晰的描述异常信息，因此，可以自定义一个异常，专门描述校验用户名过程中发生的异常。</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line">package cn.bytecollege;</span><br><span class="line">/**</span><br><span class="line"> * 本例将演示自定义异常</span><br><span class="line"> * @author MR.W</span><br><span class="line"> *</span><br><span class="line"> */</span><br><span class="line">public class UsernameException extends Exception&#123;</span><br><span class="line">	public UsernameException() &#123;</span><br><span class="line">		super();</span><br><span class="line">	&#125;</span><br><span class="line">	public UsernameException(String msg)&#123;</span><br><span class="line">		super(msg);</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p>上面程序创建了AuctionException异常类，并为该异常类提供了两个构造器。尤其是第11行代码部分创建的带一个字符串参数的构造器，其执行体也非常简单，仅通过super来调用父类的构造器，正是这行super调用可以将此字符串参数传给异常对象的message属性，该message属性就是该异常对象的详细描述信息。<br>如果需要自定义Runtime异常，只需将AuctionException.java程序中的Exception基类改为RuntimeException基类，其他地方无须修改。</p>
<p>13.4.1 异常转义<br>前面介绍的异常处理方式有如下两种。</p>
<p>在出现异常的方法内捕获并处理异常，该方法的调用者将不能再次捕获该异常。<br>该方法签名中声明抛出该异常，将该异常完全交给方法调用者处理。<br>在实际应用中往往需要更复杂的处理方式——当一个异常出现时，单靠某个方法无法完全处理该异常，必须由几个方法协作才可完全处理该异常。也就是说，在异常出现的当前方法中，程序只对异常进行部分处理，还有些处理需要在该方法的调用者中才能完成，所以应该再次抛出异常，让该方法的调用者也能捕获到异常。为了实现这种通过多个方法协作处理同一个异常的情形，可以在catch块中结合throw语句来完成。如下例子程序示范了这种catch和throw同时使用的方法。</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br></pre></td><td class="code"><pre><span class="line">package cn.bytecollege.ExceptionDemo;</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">//自定义UsenameCheckedException异常类，继承Exception类</span><br><span class="line">public class UsenameCheckedException extends Exception&#123;</span><br><span class="line">    public UsenameCheckedException (String msg)&#123;</span><br><span class="line">        //调用父类的构造方法</span><br><span class="line">        super(msg);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line">class User&#123;</span><br><span class="line">    String username;</span><br><span class="line">    public String checked(String username)throws UsenameCheckedException&#123;</span><br><span class="line">        if (username.equals(&quot;&quot;))&#123;</span><br><span class="line">            throw new UsenameCheckedException(&quot;用户名不能为空&quot;);</span><br><span class="line">        &#125;else &#123;</span><br><span class="line">            return username;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line">class Demo&#123;</span><br><span class="line">    public static void main(String[] args) &#123;</span><br><span class="line">        User user = new User();</span><br><span class="line"></span><br><span class="line">        try&#123;</span><br><span class="line">            user.checked(&quot;&quot;);</span><br><span class="line">        &#125;catch (UsenameCheckedException e)&#123;</span><br><span class="line">            throw new RuntimeException(&quot;用户名不能为空&quot;);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>

<p>13.5 访问异常信息<br>如果程序需要在 catch 块中访问异常对象的相关信息，则可以通过访问 catch 块的后异常形参来获得。当 Java运行时决定调用某个 catch 块来处理该异常对象时，会将异常对象赋给 catch 块后的异常参数，程序即可通过该参数来获得异常的相关信息。 所有的异常对象都包含了如下几个常用方法。</p>
<p>getMessage()∶ 返回该异常的详细描述字符串。<br>printStackTrace()∶将该异常的跟踪栈信息输出到标准错误输出。<br>getStackTrace()∶ 返回该异常的跟踪栈信息。下面例子程序演示了程序如何访问异常信息。</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br></pre></td><td class="code"><pre><span class="line">package cn.bytecollege.ExceptionDemo;</span><br><span class="line"></span><br><span class="line">public class ExceptionMethod &#123;</span><br><span class="line">    public static void main(String[] args) &#123;</span><br><span class="line">        try&#123;</span><br><span class="line">            int i = 5/0;</span><br><span class="line">        &#125; catch (ArithmeticException e) &#123;</span><br><span class="line">            //将该异常的跟踪栈信息输出到标准错误输出</span><br><span class="line">            e.printStackTrace();</span><br><span class="line">            //返回该异常的详细描述字符串</span><br><span class="line">            e.getMessage();</span><br><span class="line">            //返回该异常的跟踪栈信息</span><br><span class="line">            e.getStackTrace();</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p>上面程序调用了 Exception 对象的 getMessage（）方法来得到异常对象的详细信息，也使用了 printStackTrace（）方法来打印该异常的跟踪信息。运行上面程序，会看到下图所示的界面。<br>image.png</p>
<p>13.6 异常链<br>对于真实的企业级应用而言，常常有严格的分层关系，层与层之间有非常清晰的划分，上层功能的实现严格依赖于下层的API，也不会跨层访问。<br>把底层的原始异常直接传给用户是一种不负责任的表现。通常的做法是：程序先捕获原始异常，然后逐级向上抛出，直到某一层将该异常进行处理。<br>下面的程序将演示这种情况：</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br></pre></td><td class="code"><pre><span class="line">package cn.bytecollege.ExceptionDemo;</span><br><span class="line"></span><br><span class="line">public class ExceptionDemo2 &#123;</span><br><span class="line">    class A &#123;</span><br><span class="line">        public void a()&#123;</span><br><span class="line">            try&#123;</span><br><span class="line">                B.b();</span><br><span class="line">            &#125; catch (Exception e) &#123;</span><br><span class="line">                e.printStackTrace();</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">    static class B&#123;</span><br><span class="line">        public static void b() throws Exception &#123;</span><br><span class="line">            C.c();</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">    static class C&#123;</span><br><span class="line">        public static void c() throws Exception&#123;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br></pre></td></tr></table></figure></div>
        </div>
        
            <div class="kratos-copyright text-center clearfix">
                <h5 itemprop="copyrightNotice">本作品采用 <a rel="license nofollow" target="_blank" href="https://creativecommons.org/licenses/by-sa/4.0/">知识共享署名-相同方式共享 4.0 国际许可协议</a> 进行许可</h5>
            </div>
        
        <footer class="kratos-entry-footer clearfix">
            
                <div class="post-like-donate text-center clearfix" id="post-like-donate">
                
                
                    <a class="share" href="javascript:;"><i class="fa fa-share-alt"></i> 分享</a>
                    <div class="share-wrap" style="display: none;">
    <div class="share-group">
        <a href="javascript:;" class="share-plain qq" onclick="share('qq');" rel="nofollow">
            <div class="icon-wrap">
                <i class="fa fa-qq"></i>
            </div>
        </a>
        <a href="javascript:;" class="share-plain qzone" onclick="share('qzone');" rel="nofollow">
            <div class="icon-wrap">
                <i class="fa fa-star"></i>
            </div>
        </a>
        <a href="javascript:;" class="share-plain weixin pop style-plain" rel="nofollow">
            <div class="icon-wrap">
                <i class="fa fa-weixin"></i>
            </div>
            <div class="share-int">
                <div class="qrcode" id="wechat-qr"></div>
                <p>打开微信“扫一扫”，打开网页后点击屏幕右上角分享按钮</p>
            </div>
        </a>
        <a href="javascript:;" class="share-plain weibo" onclick="share('weibo');" rel="nofollow">
            <div class="icon-wrap">
                <i class="fa fa-weibo"></i>
            </div>
        </a>
        <a href="javascript:;" class="share-plain facebook style-plain" onclick="share('facebook');" rel="nofollow">
            <div class="icon-wrap">
                <i class="fa fa-facebook"></i>
            </div>
        </a>
        <a href="javascript:;" class="share-plain twitter style-plain" onclick="share('twitter');" rel="nofollow">
            <div class="icon-wrap">
                <i class="fa fa-twitter"></i>
            </div>
        </a>
    </div>
    <script type="text/javascript">
        $(()=>{
            new QRCode("wechat-qr", {
                text: "https://simon-yian.github.io/2022/08/10/xianTrain20-Exception/",
                width: 150,
                height: 150,
                correctLevel : QRCode.CorrectLevel.H
            });
        });
        function share(dest) {
            const qqBase        = "https://connect.qq.com/widget/shareqq/index.html?";
            const weiboBase     = "https://service.weibo.com/share/share.php?";
            const qzoneBase     = "https://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?";
            const facebookBase  = "https://www.facebook.com/sharer/sharer.php?";
            const twitterBase   = "https://twitter.com/intent/tweet?";
            const hostUrl       = "https://simon-yian.github.io/2022/08/10/xianTrain20-Exception/";
            const title         = "「异常」";
            const excerpt       = `***&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Java基础学习打卡第2天`;
            let _URL;
            switch (dest) {
                case "qq"       : _URL = qqBase+"url="+hostUrl+"&title="+title+"&desc=&summary="+excerpt+"&site=cxpy";     break;
                case "weibo"    : _URL = weiboBase+"url="+hostUrl+"&title="+title+excerpt;                                 break;
                case "qzone"    : _URL = qzoneBase+"url="+hostUrl+"&title="+title+"&desc=&summary="+excerpt+"&site=cxpy";  break;
                case "facebook" : _URL = facebookBase+"u="+hostUrl;                                                        break;
                case "twitter"  : _URL = twitterBase+"text="+title+excerpt+"&url="+hostUrl;                                break;
            }
            window.open(_URL);
        };
    </script>
</div>
                
                </div>
            
            <div class="footer-tag clearfix">
                <div class="pull-left">
                <i class="fa fa-tags"></i>
                    
                </div>
                <div class="pull-date">
                    <time datetime="2022-08-10T12:23:08.000Z" itemprop="dateModified">最后编辑：2022-08-10</time>
                </div>
            </div>
        </footer>
    </div>
    
        <nav class="navigation post-navigation clearfix" role="navigation">
            
            <div class="nav-previous clearfix">
                <a title=" 泛型" href="/2022/08/10/xianTrain19-genericParadigm/">&lt; 上一篇</a>
            </div>
            
            
            <div class="nav-next clearfix">
                <a title=" 线程" href="/2022/08/10/xianTrain22-Thread/">下一篇 &gt;</a>
            </div>
            
        </nav>
    
    
</article>

        

            </section>

        

                
            

<section id="kratos-widget-area" class="col-md-4 hidden-xs hidden-sm">
    <!-- 文章和页面根据splitter来分割，没有的话就从头开始设置为sticky -->
    
    
                <aside id="krw-about" class="widget widget-kratos-about clearfix">
    <div class="photo-background"></div>
    <div class="photo-wrapper clearfix">
        <div class="photo-wrapper-tip text-center">
            <img class="about-photo" src="/images/avatar.webp" loading="lazy" decoding="auto" />
        </div>
    </div>
    <div class="textwidget">
        <p class="text-center"></p>
    </div>
    <div class="site-meta">
        <a class="meta-item" href="/archives/">
            <span class="title">
                文章
            </span>
            <span class="count">
                38
            </span>
        </a>
        <a class="meta-item" href="/categories/">
            <span class="title">
                分类
            </span>
            <span class="count">
                9
            </span>
        </a>
        <a class="meta-item" href="/tags/">
            <span class="title">
                标签
            </span>
            <span class="count">
                0
            </span>
        </a>
    </div>
</aside>
            
                    <div class="sticky-area">
                
                
  <aside id="krw-categories" class="widget widget-kratos-categories clearfix">
    <h4 class="widget-title"><i class="fa fa-folder"></i>分类目录</h4>
      <ul class="category-list"><li class="category-list-item"><a class="category-list-link" href="/categories/LeetCode/">LeetCode</a><span class="category-list-count">1</span></li><li class="category-list-item"><a class="category-list-link" href="/categories/Python%E7%AC%94%E8%AE%B0/">Python笔记</a><span class="category-list-count">1</span></li><li class="category-list-item"><a class="category-list-link" href="/categories/VMware/">VMware</a><span class="category-list-count">1</span></li><li class="category-list-item"><a class="category-list-link" href="/categories/XiAnTrain/">XiAnTrain</a><span class="category-list-count">17</span></li><li class="category-list-item"><a class="category-list-link" href="/categories/XiAnTrain-java%E9%AB%98%E7%BA%A7%E7%AF%87/">XiAnTrain - java高级篇</a><span class="category-list-count">7</span></li><li class="category-list-item"><a class="category-list-link" href="/categories/XiAnTrain-java%E5%88%9D%E7%BA%A7%E7%AF%87/">XiAnTrain -java初级篇</a><span class="category-list-count">1</span></li><li class="category-list-item"><a class="category-list-link" href="/categories/algorithm/">algorithm</a><span class="category-list-count">2</span></li><li class="category-list-item"><a class="category-list-link" href="/categories/fatal/">fatal</a><span class="category-list-count">1</span></li><li class="category-list-item"><a class="category-list-link" href="/categories/hexo/">hexo</a><span class="category-list-count">3</span></li></ul>
  </aside>


            
                
            
                
  <aside id="krw-posts" class="widget widget-kratos-posts">
  <h4 class="widget-title"><i class="fa fa-file"></i>最新文章</h4>
  <div class="tab-content">
      <ul class="list-group">
        
        
          
          
            <a class="list-group-item" href="/2022/09/17/jvmCommonParameters/"><i class="fa  fa-book"></i> JVM常用参数</a>
            
          
        
          
          
            <a class="list-group-item" href="/2022/09/17/xianTrain26-JavaNewCharacteristic/"><i class="fa  fa-book"></i> java新特性</a>
            
          
        
          
          
            <a class="list-group-item" href="/2022/09/17/xianTrain24-reflex/"><i class="fa  fa-book"></i> 反射和注解</a>
            
          
        
          
          
            <a class="list-group-item" href="/2022/08/10/xianTrain21-IOStream/"><i class="fa  fa-book"></i> IO流</a>
            
          
        
          
          
            <a class="list-group-item" href="/2022/08/10/xianTrain22-Thread/"><i class="fa  fa-book"></i> 线程</a>
            
          
        
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
      </ul>
  </div>
  </aside>

            
    </div>
</section>
        
        </div>
    </div>
</div>
<footer>
    <div id="footer"  class="ap-lrc"  >
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 footer-list text-center">
                    <ul class="kratos-social-icons">
                        
                        
                        <li><a target="_blank" rel="nofollow" href="https://t.me/CandyUnion"><i class="fa fa-telegram"></i></a></li>
                        
                        
                        
                        <li><a target="_blank" rel="me" href="https://nya.one/@Candinya"><i class="fa fa fa-share-alt-square"></i></a></li>
                        <li><a target="_blank" rel="nofollow" href="https://github.com/Candinya"><i class="fa fa-github"></i></a></li>
                        
                    </ul>
                    <ul class="kratos-copyright">
                        <div>
                            <li>&copy; 2022 simon·yian'Blog 版权所有.</li>
                            <li>本站已运行<span id="span_dt">Loading...</span></li>
                        </div>
                        <div>
                            <li>Theme <a href="https://github.com/Candinya/Kratos-Rebirth" target="_blank">Kratos:Rebirth</a></li>
                            <li>Site built with&nbsp;<i class="fa fa-heart throb" style="color:#d43f57"></i>&nbsp;by simon·yi an.</li>
                        </div>
                        <div>
                            <li>Powered by <a href="https://hexo.io" target="_blank" rel="nofollow">Hexo</a></li>
                            <li>Hosted on <a href="https://github.io" target="_blank">Github Pages</a></li>
                        </div>
                        <div>
                            
                            
                        </div>
                    </ul>
                </div>
            </div>
        </div>
        <div class="kr-tool text-center">
            <div class="tool">
                
                    <div class="box search-box">
                        <a href="/search/">
                            <span class="fa fa-search"></span>
                        </a>
                    </div>
                
                
                    <div class="box theme-box" id="darkmode-switch">
                        <span class="fa fa-adjust"></span>
                    </div>
                
                
            </div>
            <div class="box gotop-box">
                <span class="fa fa-chevron-up"></span>
            </div>
        </div>
    </div>
</footer>
</div>
</div>

        <script defer src="/vendors/bootstrap@3.3.4/dist/js/bootstrap.min.js"></script>
<script defer src="/vendors/nprogress@0.2.0/nprogress.js"></script>
<script>
    if (!window.kr) {
        window.kr = {};
    }
    window.kr.notMobile = (!(navigator.userAgent.match(/(phone|pad|pod|iPhone|iPod|ios|iPad|Android|Mobile|BlackBerry|IEMobile|MQQBrowser|JUC|Fennec|wOSBrowser|BrowserNG|WebOS|Symbian|Windows Phone)/i)));
    window.kr.siteRoot = "/";
</script>


    <script async src="/js/candy.min.js"></script>



    <script defer src="/vendors/aplayer@1.10.1/dist/APlayer.min.js"></script>
    
    <script defer src="/vendors/meting@2.0.1/dist/Meting.min.js"></script>
    <meting-js
        server="netease"
        type="playlist"
        id="3204190542"
        order="random"
        fixed="true"
    >
    </meting-js>



    <script defer src="/vendors/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>

<script defer src="/vendors/clipboard@2.0.6/dist/clipboard.min.js"></script>
<script defer src="/js/kratosr.min.js"></script>
<script defer src="/js/pjax.min.js"></script>



<!-- Extra support for third-party plguins  -->


    </body>
</html>